// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250615050356_Update competitions category")]
    partial class Updatecompetitionscategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FisheryFishSpecies", b =>
                {
                    b.Property<int>("FisheryId")
                        .HasColumnType("integer");

                    b.Property<int>("FishSpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("FisheryId", "FishSpeciesId");

                    b.HasIndex("FishSpeciesId");

                    b.ToTable("FisheryFishSpecies", (string)null);
                });

            modelBuilder.Entity("Fishio.Domain.Entities.CategoryDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowManualWinnerAssignment")
                        .HasColumnType("boolean");

                    b.Property<string>("CalculationLogic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("RequiresSpecificFishSpecies")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("CategoryDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowManualWinnerAssignment = false,
                            CalculationLogic = "SumValue",
                            Created = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Zwycięzcą zostaje uczestnik z największą długością wszystkich swoich złowionych ryb.",
                            EntityType = "ParticipantAggregateCatches",
                            IsGlobal = true,
                            LastModified = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Metric = "LengthCm",
                            Name = "Długość złowionych ryb",
                            RequiresSpecificFishSpecies = false,
                            Type = "MainScoring"
                        },
                        new
                        {
                            Id = 2,
                            AllowManualWinnerAssignment = false,
                            CalculationLogic = "SumValue",
                            Created = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Zwycięzcą zostaje uczestnik z największą wagą wszystkich swoich złowionych ryb.",
                            EntityType = "ParticipantAggregateCatches",
                            IsGlobal = true,
                            LastModified = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Metric = "WeightKg",
                            Name = "Waga złowionych ryb",
                            RequiresSpecificFishSpecies = false,
                            Type = "MainScoring"
                        },
                        new
                        {
                            Id = 3,
                            AllowManualWinnerAssignment = false,
                            CalculationLogic = "SumValue",
                            Created = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Zwycięzcą zostaje uczestnik, który złowił najwięcej ryb (sztuk).",
                            EntityType = "ParticipantAggregateCatches",
                            IsGlobal = true,
                            LastModified = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Metric = "FishCount",
                            Name = "Liczba Złowionych Ryb",
                            RequiresSpecificFishSpecies = false,
                            Type = "MainScoring"
                        },
                        new
                        {
                            Id = 4,
                            AllowManualWinnerAssignment = true,
                            CalculationLogic = "MaxValue",
                            Created = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Nagroda za najcięższą rybę zawodów, niezależnie od gatunku.",
                            EntityType = "FishCatch",
                            IsGlobal = true,
                            LastModified = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Metric = "WeightKg",
                            Name = "Najcięższa ryba zawodów",
                            RequiresSpecificFishSpecies = false,
                            Type = "SpecialAchievement"
                        },
                        new
                        {
                            Id = 5,
                            AllowManualWinnerAssignment = true,
                            CalculationLogic = "MaxValue",
                            Created = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Nagroda za najdłuższą rybę zawodów, niezależnie od gatunku.",
                            EntityType = "FishCatch",
                            IsGlobal = true,
                            LastModified = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Metric = "LengthCm",
                            Name = "Najdłuższa ryba zawodów",
                            RequiresSpecificFishSpecies = false,
                            Type = "SpecialAchievement"
                        },
                        new
                        {
                            Id = 6,
                            AllowManualWinnerAssignment = true,
                            CalculationLogic = "MaxValue",
                            Created = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Nagroda za największą rybę wybranego gatunku.",
                            EntityType = "FishCatch",
                            IsGlobal = true,
                            LastModified = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Metric = "LengthCm",
                            Name = "Najdłuższa ryba określonego gatunku",
                            RequiresSpecificFishSpecies = true,
                            Type = "SpecialAchievement"
                        },
                        new
                        {
                            Id = 7,
                            AllowManualWinnerAssignment = true,
                            CalculationLogic = "MaxValue",
                            Created = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Nagroda za największą rybę wybranego gatunku.",
                            EntityType = "FishCatch",
                            IsGlobal = true,
                            LastModified = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Metric = "WeightKg",
                            Name = "Najcięższa ryba określonego gatunku",
                            RequiresSpecificFishSpecies = true,
                            Type = "SpecialAchievement"
                        },
                        new
                        {
                            Id = 8,
                            AllowManualWinnerAssignment = false,
                            CalculationLogic = "MaxValue",
                            Created = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Nagroda za największą różnorodność gatunków.",
                            EntityType = "ParticipantAggregateCatches",
                            IsGlobal = true,
                            LastModified = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Metric = "SpeciesVariety",
                            Name = "Największa Różnorodność Gatunków",
                            RequiresSpecificFishSpecies = false,
                            Type = "SpecialAchievement"
                        });
                });

            modelBuilder.Entity("Fishio.Domain.Entities.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("FisheryId")
                        .HasColumnType("integer");

                    b.Property<string>("ImagePublicId")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("integer");

                    b.Property<string>("ResultsToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Rules")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FisheryId");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("ResultsToken")
                        .IsUnique();

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("Fishio.Domain.Entities.CompetitionCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryDefinitionId")
                        .HasColumnType("integer");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("CustomDescriptionOverride")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("CustomNameOverride")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("FishSpeciesId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPrimaryScoring")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<int>("MaxWinnersToDisplay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryDefinitionId");

                    b.HasIndex("FishSpeciesId");

                    b.HasIndex("CompetitionId", "SortOrder");

                    b.ToTable("CompetitionCategories");
                });

            modelBuilder.Entity("Fishio.Domain.Entities.CompetitionFishCatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CatchTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("FishSpeciesId")
                        .HasColumnType("integer");

                    b.Property<int>("JudgeId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Length")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("LengthCm");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(7, 3)
                        .HasColumnType("numeric(7,3)")
                        .HasColumnName("WeightKg");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("FishSpeciesId");

                    b.HasIndex("JudgeId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("CompetitionFishCatches");
                });

            modelBuilder.Entity("Fishio.Domain.Entities.CompetitionParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AddedByOrganizer")
                        .HasColumnType("boolean");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("GuestIdentifier")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GuestName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CompetitionId", "GuestIdentifier")
                        .IsUnique()
                        .HasFilter("\"GuestIdentifier\" IS NOT NULL");

                    b.HasIndex("CompetitionId", "UserId", "Role")
                        .IsUnique()
                        .HasFilter("\"UserId\" IS NOT NULL");

                    b.ToTable("CompetitionParticipants");
                });

            modelBuilder.Entity("Fishio.Domain.Entities.FishSpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FishSpecies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "/images/fish/amur-bialy.gif",
                            Name = "Amur biały"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "/images/fish/bolen.gif",
                            Name = "Boleń"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "/images/fish/brzana.gif",
                            Name = "Brzana"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "/images/fish/certa.gif",
                            Name = "Certa"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "/images/fish/jaz.gif",
                            Name = "Jaź"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "/images/fish/jelec.gif",
                            Name = "Jelec"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "/images/fish/karas.gif",
                            Name = "Karaś"
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "/images/fish/karas-srebrzysty.gif",
                            Name = "Karaś srebrzysty"
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "/images/fish/karp.gif",
                            Name = "Karp"
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "/images/fish/kielb.gif",
                            Name = "Kiełb"
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "/images/fish/klen.gif",
                            Name = "Kleń"
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "/images/fish/koza.gif",
                            Name = "Koza"
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "/images/fish/krap.gif",
                            Name = "Krap"
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "/images/fish/leszcz.gif",
                            Name = "Leszcz"
                        },
                        new
                        {
                            Id = 15,
                            ImageUrl = "/images/fish/lin.gif",
                            Name = "Lin"
                        },
                        new
                        {
                            Id = 16,
                            ImageUrl = "/images/fish/lipien.gif",
                            Name = "Lipień"
                        },
                        new
                        {
                            Id = 17,
                            ImageUrl = "/images/fish/mietus.gif",
                            Name = "Miętus"
                        },
                        new
                        {
                            Id = 18,
                            ImageUrl = "/images/fish/okon.gif",
                            Name = "Okoń"
                        },
                        new
                        {
                            Id = 19,
                            ImageUrl = "/images/fish/piskorz.gif",
                            Name = "Piskorz"
                        },
                        new
                        {
                            Id = 20,
                            ImageUrl = "/images/fish/ploc.gif",
                            Name = "Płoć"
                        },
                        new
                        {
                            Id = 21,
                            ImageUrl = "/images/fish/pstrag-potokowy.gif",
                            Name = "Pstrąg potokowy"
                        },
                        new
                        {
                            Id = 22,
                            ImageUrl = "/images/fish/pstrag-zrodlany.gif",
                            Name = "Pstrąg źródlany"
                        },
                        new
                        {
                            Id = 23,
                            ImageUrl = "/images/fish/rozanka.gif",
                            Name = "Różanka"
                        },
                        new
                        {
                            Id = 24,
                            ImageUrl = "/images/fish/sandacz.gif",
                            Name = "Sandacz"
                        },
                        new
                        {
                            Id = 25,
                            ImageUrl = "/images/fish/sliz.gif",
                            Name = "Śliż"
                        },
                        new
                        {
                            Id = 26,
                            ImageUrl = "/images/fish/strzebla-potokowa.gif",
                            Name = "Strzebla potokowa"
                        },
                        new
                        {
                            Id = 27,
                            ImageUrl = "/images/fish/sum.gif",
                            Name = "Sum"
                        },
                        new
                        {
                            Id = 28,
                            ImageUrl = "/images/fish/swinka.gif",
                            Name = "Świńka"
                        },
                        new
                        {
                            Id = 29,
                            ImageUrl = "/images/fish/szczupak.gif",
                            Name = "Szczupak"
                        },
                        new
                        {
                            Id = 30,
                            ImageUrl = "/images/fish/tolpyga-biala.gif",
                            Name = "Tołpyga biała"
                        },
                        new
                        {
                            Id = 31,
                            ImageUrl = "/images/fish/ukleja.gif",
                            Name = "Ukleja"
                        },
                        new
                        {
                            Id = 32,
                            ImageUrl = "/images/fish/wegorz-europejski.gif",
                            Name = "Węgorz europejski"
                        },
                        new
                        {
                            Id = 33,
                            ImageUrl = "/images/fish/wzdrega.gif",
                            Name = "Wzdręga"
                        });
                });

            modelBuilder.Entity("Fishio.Domain.Entities.Fishery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("ImagePublicId")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Fisheries");
                });

            modelBuilder.Entity("Fishio.Domain.Entities.LogbookEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CatchTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("FishSpeciesId")
                        .HasColumnType("integer");

                    b.Property<int?>("FisheryId")
                        .HasColumnType("integer");

                    b.Property<string>("ImagePublicId")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Length")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("LengthCm");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(7, 3)
                        .HasColumnType("numeric(7,3)")
                        .HasColumnName("WeightKg");

                    b.HasKey("Id");

                    b.HasIndex("FishSpeciesId");

                    b.HasIndex("FisheryId");

                    b.HasIndex("UserId");

                    b.ToTable("LogbookEntries");
                });

            modelBuilder.Entity("Fishio.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClerkUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ClerkUserId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FisheryFishSpecies", b =>
                {
                    b.HasOne("Fishio.Domain.Entities.FishSpecies", null)
                        .WithMany()
                        .HasForeignKey("FishSpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fishio.Domain.Entities.Fishery", null)
                        .WithMany()
                        .HasForeignKey("FisheryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fishio.Domain.Entities.Competition", b =>
                {
                    b.HasOne("Fishio.Domain.Entities.Fishery", "Fishery")
                        .WithMany("Competitions")
                        .HasForeignKey("FisheryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fishio.Domain.Entities.User", "Organizer")
                        .WithMany("OrganizedCompetitions")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Fishio.Domain.ValueObjects.DateTimeRange", "Schedule", b1 =>
                        {
                            b1.Property<int>("CompetitionId")
                                .HasColumnType("integer");

                            b1.Property<DateTimeOffset>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("EndTime");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("StartTime");

                            b1.HasKey("CompetitionId");

                            b1.ToTable("Competitions");

                            b1.WithOwner()
                                .HasForeignKey("CompetitionId");
                        });

                    b.Navigation("Fishery");

                    b.Navigation("Organizer");

                    b.Navigation("Schedule")
                        .IsRequired();
                });

            modelBuilder.Entity("Fishio.Domain.Entities.CompetitionCategory", b =>
                {
                    b.HasOne("Fishio.Domain.Entities.CategoryDefinition", "CategoryDefinition")
                        .WithMany("CompetitionCategories")
                        .HasForeignKey("CategoryDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fishio.Domain.Entities.Competition", "Competition")
                        .WithMany("Categories")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fishio.Domain.Entities.FishSpecies", "FishSpecies")
                        .WithMany("CompetitionCategories")
                        .HasForeignKey("FishSpeciesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CategoryDefinition");

                    b.Navigation("Competition");

                    b.Navigation("FishSpecies");
                });

            modelBuilder.Entity("Fishio.Domain.Entities.CompetitionFishCatch", b =>
                {
                    b.HasOne("Fishio.Domain.Entities.Competition", "Competition")
                        .WithMany("FishCatches")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fishio.Domain.Entities.FishSpecies", "FishSpecies")
                        .WithMany("CompetitionFishCatches")
                        .HasForeignKey("FishSpeciesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fishio.Domain.Entities.User", "Judge")
                        .WithMany("JudgedFishCatches")
                        .HasForeignKey("JudgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fishio.Domain.Entities.CompetitionParticipant", "Participant")
                        .WithMany("FishCatches")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("FishSpecies");

                    b.Navigation("Judge");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Fishio.Domain.Entities.CompetitionParticipant", b =>
                {
                    b.HasOne("Fishio.Domain.Entities.Competition", "Competition")
                        .WithMany("Participants")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fishio.Domain.Entities.User", "User")
                        .WithMany("CompetitionParticipations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Competition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fishio.Domain.Entities.Fishery", b =>
                {
                    b.HasOne("Fishio.Domain.Entities.User", "User")
                        .WithMany("CreatedFisheries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fishio.Domain.Entities.LogbookEntry", b =>
                {
                    b.HasOne("Fishio.Domain.Entities.FishSpecies", "FishSpecies")
                        .WithMany("LogbookEntries")
                        .HasForeignKey("FishSpeciesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fishio.Domain.Entities.Fishery", "Fishery")
                        .WithMany("LogbookEntries")
                        .HasForeignKey("FisheryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fishio.Domain.Entities.User", "User")
                        .WithMany("LogbookEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FishSpecies");

                    b.Navigation("Fishery");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fishio.Domain.Entities.CategoryDefinition", b =>
                {
                    b.Navigation("CompetitionCategories");
                });

            modelBuilder.Entity("Fishio.Domain.Entities.Competition", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("FishCatches");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Fishio.Domain.Entities.CompetitionParticipant", b =>
                {
                    b.Navigation("FishCatches");
                });

            modelBuilder.Entity("Fishio.Domain.Entities.FishSpecies", b =>
                {
                    b.Navigation("CompetitionCategories");

                    b.Navigation("CompetitionFishCatches");

                    b.Navigation("LogbookEntries");
                });

            modelBuilder.Entity("Fishio.Domain.Entities.Fishery", b =>
                {
                    b.Navigation("Competitions");

                    b.Navigation("LogbookEntries");
                });

            modelBuilder.Entity("Fishio.Domain.Entities.User", b =>
                {
                    b.Navigation("CompetitionParticipations");

                    b.Navigation("CreatedFisheries");

                    b.Navigation("JudgedFishCatches");

                    b.Navigation("LogbookEntries");

                    b.Navigation("OrganizedCompetitions");
                });
#pragma warning restore 612, 618
        }
    }
}
