/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from '../axios';
import type {
  AddParticipantCommand,
  AssignJudgeCommand,
  CancelCompetitionCommand,
  CompetitionDetailsDto,
  CompetitionFishCatchDto,
  CompetitionSummaryDtoPaginatedList,
  CreateCompetitionCommand,
  GetOpenCompetitionsListParams,
  GetUserCompetitionsListParams,
  MyCompetitionSummaryDtoPaginatedList,
  ProblemDetails,
  RecordCompetitionFishCatchCommand,
  SetToDraftCommand,
  UpdateCompetitionCategoryCommand,
  UpdateCompetitionCommand
} from '../models';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const createNewCompetition = (
  createCompetitionCommand: CreateCompetitionCommand,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<unknown>(
    {
      url: `/api/competitions`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createCompetitionCommand,
      signal
    },
    options
  );
};

export const getCreateNewCompetitionMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createNewCompetition>>,
    TError,
    { data: CreateCompetitionCommand },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createNewCompetition>>,
  TError,
  { data: CreateCompetitionCommand },
  TContext
> => {
  const mutationKey = ['createNewCompetition'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createNewCompetition>>,
    { data: CreateCompetitionCommand }
  > = (props) => {
    const { data } = props ?? {};

    return createNewCompetition(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateNewCompetitionMutationResult = NonNullable<Awaited<ReturnType<typeof createNewCompetition>>>;
export type CreateNewCompetitionMutationBody = CreateCompetitionCommand;
export type CreateNewCompetitionMutationError = ProblemDetails;

export const useCreateNewCompetition = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createNewCompetition>>,
      TError,
      { data: CreateCompetitionCommand },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createNewCompetition>>,
  TError,
  { data: CreateCompetitionCommand },
  TContext
> => {
  const mutationOptions = getCreateNewCompetitionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getOpenCompetitionsList = (
  params: GetOpenCompetitionsListParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<CompetitionSummaryDtoPaginatedList>(
    { url: `/api/competitions/open`, method: 'GET', params, signal },
    options
  );
};

export const getGetOpenCompetitionsListQueryKey = (params: GetOpenCompetitionsListParams) => {
  return [`/api/competitions/open`, ...(params ? [params] : [])] as const;
};

export const getGetOpenCompetitionsListQueryOptions = <
  TData = Awaited<ReturnType<typeof getOpenCompetitionsList>>,
  TError = unknown
>(
  params: GetOpenCompetitionsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpenCompetitionsList>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetOpenCompetitionsListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getOpenCompetitionsList>>> = ({ signal }) =>
    getOpenCompetitionsList(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getOpenCompetitionsList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOpenCompetitionsListQueryResult = NonNullable<Awaited<ReturnType<typeof getOpenCompetitionsList>>>;
export type GetOpenCompetitionsListQueryError = unknown;

export function useGetOpenCompetitionsList<
  TData = Awaited<ReturnType<typeof getOpenCompetitionsList>>,
  TError = unknown
>(
  params: GetOpenCompetitionsListParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpenCompetitionsList>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOpenCompetitionsList>>,
          TError,
          Awaited<ReturnType<typeof getOpenCompetitionsList>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOpenCompetitionsList<
  TData = Awaited<ReturnType<typeof getOpenCompetitionsList>>,
  TError = unknown
>(
  params: GetOpenCompetitionsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpenCompetitionsList>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOpenCompetitionsList>>,
          TError,
          Awaited<ReturnType<typeof getOpenCompetitionsList>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOpenCompetitionsList<
  TData = Awaited<ReturnType<typeof getOpenCompetitionsList>>,
  TError = unknown
>(
  params: GetOpenCompetitionsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpenCompetitionsList>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetOpenCompetitionsList<
  TData = Awaited<ReturnType<typeof getOpenCompetitionsList>>,
  TError = unknown
>(
  params: GetOpenCompetitionsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpenCompetitionsList>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetOpenCompetitionsListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getUserCompetitionsList = (
  params: GetUserCompetitionsListParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<MyCompetitionSummaryDtoPaginatedList>(
    { url: `/api/competitions/my`, method: 'GET', params, signal },
    options
  );
};

export const getGetUserCompetitionsListQueryKey = (params: GetUserCompetitionsListParams) => {
  return [`/api/competitions/my`, ...(params ? [params] : [])] as const;
};

export const getGetUserCompetitionsListQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserCompetitionsList>>,
  TError = ProblemDetails
>(
  params: GetUserCompetitionsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserCompetitionsList>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserCompetitionsListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserCompetitionsList>>> = ({ signal }) =>
    getUserCompetitionsList(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserCompetitionsList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserCompetitionsListQueryResult = NonNullable<Awaited<ReturnType<typeof getUserCompetitionsList>>>;
export type GetUserCompetitionsListQueryError = ProblemDetails;

export function useGetUserCompetitionsList<
  TData = Awaited<ReturnType<typeof getUserCompetitionsList>>,
  TError = ProblemDetails
>(
  params: GetUserCompetitionsListParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserCompetitionsList>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserCompetitionsList>>,
          TError,
          Awaited<ReturnType<typeof getUserCompetitionsList>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUserCompetitionsList<
  TData = Awaited<ReturnType<typeof getUserCompetitionsList>>,
  TError = ProblemDetails
>(
  params: GetUserCompetitionsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserCompetitionsList>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserCompetitionsList>>,
          TError,
          Awaited<ReturnType<typeof getUserCompetitionsList>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUserCompetitionsList<
  TData = Awaited<ReturnType<typeof getUserCompetitionsList>>,
  TError = ProblemDetails
>(
  params: GetUserCompetitionsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserCompetitionsList>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetUserCompetitionsList<
  TData = Awaited<ReturnType<typeof getUserCompetitionsList>>,
  TError = ProblemDetails
>(
  params: GetUserCompetitionsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserCompetitionsList>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetUserCompetitionsListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getCompetitionDetailsById = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<CompetitionDetailsDto>({ url: `/api/competitions/${id}`, method: 'GET', signal }, options);
};

export const getGetCompetitionDetailsByIdQueryKey = (id: number) => {
  return [`/api/competitions/${id}`] as const;
};

export const getGetCompetitionDetailsByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getCompetitionDetailsById>>,
  TError = void
>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompetitionDetailsById>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCompetitionDetailsByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCompetitionDetailsById>>> = ({ signal }) =>
    getCompetitionDetailsById(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCompetitionDetailsById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCompetitionDetailsByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getCompetitionDetailsById>>>;
export type GetCompetitionDetailsByIdQueryError = void;

export function useGetCompetitionDetailsById<
  TData = Awaited<ReturnType<typeof getCompetitionDetailsById>>,
  TError = void
>(
  id: number,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompetitionDetailsById>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompetitionDetailsById>>,
          TError,
          Awaited<ReturnType<typeof getCompetitionDetailsById>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCompetitionDetailsById<
  TData = Awaited<ReturnType<typeof getCompetitionDetailsById>>,
  TError = void
>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompetitionDetailsById>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompetitionDetailsById>>,
          TError,
          Awaited<ReturnType<typeof getCompetitionDetailsById>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCompetitionDetailsById<
  TData = Awaited<ReturnType<typeof getCompetitionDetailsById>>,
  TError = void
>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompetitionDetailsById>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetCompetitionDetailsById<
  TData = Awaited<ReturnType<typeof getCompetitionDetailsById>>,
  TError = void
>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompetitionDetailsById>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCompetitionDetailsByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const updateExistingCompetition = (
  id: number,
  updateCompetitionCommand: UpdateCompetitionCommand,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    {
      url: `/api/competitions/${id}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateCompetitionCommand
    },
    options
  );
};

export const getUpdateExistingCompetitionMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateExistingCompetition>>,
    TError,
    { id: number; data: UpdateCompetitionCommand },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateExistingCompetition>>,
  TError,
  { id: number; data: UpdateCompetitionCommand },
  TContext
> => {
  const mutationKey = ['updateExistingCompetition'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateExistingCompetition>>,
    { id: number; data: UpdateCompetitionCommand }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateExistingCompetition(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateExistingCompetitionMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateExistingCompetition>>
>;
export type UpdateExistingCompetitionMutationBody = UpdateCompetitionCommand;
export type UpdateExistingCompetitionMutationError = ProblemDetails;

export const useUpdateExistingCompetition = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateExistingCompetition>>,
      TError,
      { id: number; data: UpdateCompetitionCommand },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateExistingCompetition>>,
  TError,
  { id: number; data: UpdateCompetitionCommand },
  TContext
> => {
  const mutationOptions = getUpdateExistingCompetitionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const organizerSetsToDraft = (
  competitionId: number,
  setToDraftCommand: SetToDraftCommand,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/competitions/${competitionId}/status/set-to-draft`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: setToDraftCommand,
      signal
    },
    options
  );
};

export const getOrganizerSetsToDraftMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizerSetsToDraft>>,
    TError,
    { competitionId: number; data: SetToDraftCommand },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizerSetsToDraft>>,
  TError,
  { competitionId: number; data: SetToDraftCommand },
  TContext
> => {
  const mutationKey = ['organizerSetsToDraft'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizerSetsToDraft>>,
    { competitionId: number; data: SetToDraftCommand }
  > = (props) => {
    const { competitionId, data } = props ?? {};

    return organizerSetsToDraft(competitionId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizerSetsToDraftMutationResult = NonNullable<Awaited<ReturnType<typeof organizerSetsToDraft>>>;
export type OrganizerSetsToDraftMutationBody = SetToDraftCommand;
export type OrganizerSetsToDraftMutationError = ProblemDetails;

export const useOrganizerSetsToDraft = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof organizerSetsToDraft>>,
      TError,
      { competitionId: number; data: SetToDraftCommand },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof organizerSetsToDraft>>,
  TError,
  { competitionId: number; data: SetToDraftCommand },
  TContext
> => {
  const mutationOptions = getOrganizerSetsToDraftMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const organizerOpensRegistrations = (
  competitionId: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    { url: `/api/competitions/${competitionId}/status/open-registrations`, method: 'POST', signal },
    options
  );
};

export const getOrganizerOpensRegistrationsMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizerOpensRegistrations>>,
    TError,
    { competitionId: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizerOpensRegistrations>>,
  TError,
  { competitionId: number },
  TContext
> => {
  const mutationKey = ['organizerOpensRegistrations'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizerOpensRegistrations>>,
    { competitionId: number }
  > = (props) => {
    const { competitionId } = props ?? {};

    return organizerOpensRegistrations(competitionId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizerOpensRegistrationsMutationResult = NonNullable<
  Awaited<ReturnType<typeof organizerOpensRegistrations>>
>;

export type OrganizerOpensRegistrationsMutationError = ProblemDetails;

export const useOrganizerOpensRegistrations = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof organizerOpensRegistrations>>,
      TError,
      { competitionId: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof organizerOpensRegistrations>>,
  TError,
  { competitionId: number },
  TContext
> => {
  const mutationOptions = getOrganizerOpensRegistrationsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const organizerSchedulesCompetition = (
  competitionId: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    { url: `/api/competitions/${competitionId}/status/schedule`, method: 'POST', signal },
    options
  );
};

export const getOrganizerSchedulesCompetitionMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizerSchedulesCompetition>>,
    TError,
    { competitionId: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizerSchedulesCompetition>>,
  TError,
  { competitionId: number },
  TContext
> => {
  const mutationKey = ['organizerSchedulesCompetition'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizerSchedulesCompetition>>,
    { competitionId: number }
  > = (props) => {
    const { competitionId } = props ?? {};

    return organizerSchedulesCompetition(competitionId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizerSchedulesCompetitionMutationResult = NonNullable<
  Awaited<ReturnType<typeof organizerSchedulesCompetition>>
>;

export type OrganizerSchedulesCompetitionMutationError = ProblemDetails;

export const useOrganizerSchedulesCompetition = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof organizerSchedulesCompetition>>,
      TError,
      { competitionId: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof organizerSchedulesCompetition>>,
  TError,
  { competitionId: number },
  TContext
> => {
  const mutationOptions = getOrganizerSchedulesCompetitionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const organizerReopensRegistrations = (
  competitionId: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    { url: `/api/competitions/${competitionId}/status/reopen-registrations`, method: 'POST', signal },
    options
  );
};

export const getOrganizerReopensRegistrationsMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizerReopensRegistrations>>,
    TError,
    { competitionId: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizerReopensRegistrations>>,
  TError,
  { competitionId: number },
  TContext
> => {
  const mutationKey = ['organizerReopensRegistrations'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizerReopensRegistrations>>,
    { competitionId: number }
  > = (props) => {
    const { competitionId } = props ?? {};

    return organizerReopensRegistrations(competitionId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizerReopensRegistrationsMutationResult = NonNullable<
  Awaited<ReturnType<typeof organizerReopensRegistrations>>
>;

export type OrganizerReopensRegistrationsMutationError = ProblemDetails;

export const useOrganizerReopensRegistrations = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof organizerReopensRegistrations>>,
      TError,
      { competitionId: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof organizerReopensRegistrations>>,
  TError,
  { competitionId: number },
  TContext
> => {
  const mutationOptions = getOrganizerReopensRegistrationsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const organizerStartsCompetition = (
  competitionId: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    { url: `/api/competitions/${competitionId}/status/start`, method: 'POST', signal },
    options
  );
};

export const getOrganizerStartsCompetitionMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizerStartsCompetition>>,
    TError,
    { competitionId: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizerStartsCompetition>>,
  TError,
  { competitionId: number },
  TContext
> => {
  const mutationKey = ['organizerStartsCompetition'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizerStartsCompetition>>,
    { competitionId: number }
  > = (props) => {
    const { competitionId } = props ?? {};

    return organizerStartsCompetition(competitionId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizerStartsCompetitionMutationResult = NonNullable<
  Awaited<ReturnType<typeof organizerStartsCompetition>>
>;

export type OrganizerStartsCompetitionMutationError = ProblemDetails;

export const useOrganizerStartsCompetition = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof organizerStartsCompetition>>,
      TError,
      { competitionId: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof organizerStartsCompetition>>,
  TError,
  { competitionId: number },
  TContext
> => {
  const mutationOptions = getOrganizerStartsCompetitionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const organizerFinishesCompetition = (
  competitionId: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    { url: `/api/competitions/${competitionId}/status/finish`, method: 'POST', signal },
    options
  );
};

export const getOrganizerFinishesCompetitionMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizerFinishesCompetition>>,
    TError,
    { competitionId: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizerFinishesCompetition>>,
  TError,
  { competitionId: number },
  TContext
> => {
  const mutationKey = ['organizerFinishesCompetition'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizerFinishesCompetition>>,
    { competitionId: number }
  > = (props) => {
    const { competitionId } = props ?? {};

    return organizerFinishesCompetition(competitionId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizerFinishesCompetitionMutationResult = NonNullable<
  Awaited<ReturnType<typeof organizerFinishesCompetition>>
>;

export type OrganizerFinishesCompetitionMutationError = ProblemDetails;

export const useOrganizerFinishesCompetition = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof organizerFinishesCompetition>>,
      TError,
      { competitionId: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof organizerFinishesCompetition>>,
  TError,
  { competitionId: number },
  TContext
> => {
  const mutationOptions = getOrganizerFinishesCompetitionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const organizerCancelsCompetition = (
  competitionId: number,
  cancelCompetitionCommand: CancelCompetitionCommand,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/api/competitions/${competitionId}/status/cancel`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: cancelCompetitionCommand,
      signal
    },
    options
  );
};

export const getOrganizerCancelsCompetitionMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizerCancelsCompetition>>,
    TError,
    { competitionId: number; data: CancelCompetitionCommand },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizerCancelsCompetition>>,
  TError,
  { competitionId: number; data: CancelCompetitionCommand },
  TContext
> => {
  const mutationKey = ['organizerCancelsCompetition'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizerCancelsCompetition>>,
    { competitionId: number; data: CancelCompetitionCommand }
  > = (props) => {
    const { competitionId, data } = props ?? {};

    return organizerCancelsCompetition(competitionId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizerCancelsCompetitionMutationResult = NonNullable<
  Awaited<ReturnType<typeof organizerCancelsCompetition>>
>;
export type OrganizerCancelsCompetitionMutationBody = CancelCompetitionCommand;
export type OrganizerCancelsCompetitionMutationError = ProblemDetails;

export const useOrganizerCancelsCompetition = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof organizerCancelsCompetition>>,
      TError,
      { competitionId: number; data: CancelCompetitionCommand },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof organizerCancelsCompetition>>,
  TError,
  { competitionId: number; data: CancelCompetitionCommand },
  TContext
> => {
  const mutationOptions = getOrganizerCancelsCompetitionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const userJoinsCompetition = (
  competitionId: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<unknown>(
    { url: `/api/competitions/${competitionId}/participants/join`, method: 'POST', signal },
    options
  );
};

export const getUserJoinsCompetitionMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userJoinsCompetition>>,
    TError,
    { competitionId: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userJoinsCompetition>>,
  TError,
  { competitionId: number },
  TContext
> => {
  const mutationKey = ['userJoinsCompetition'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof userJoinsCompetition>>, { competitionId: number }> = (
    props
  ) => {
    const { competitionId } = props ?? {};

    return userJoinsCompetition(competitionId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserJoinsCompetitionMutationResult = NonNullable<Awaited<ReturnType<typeof userJoinsCompetition>>>;

export type UserJoinsCompetitionMutationError = ProblemDetails;

export const useUserJoinsCompetition = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof userJoinsCompetition>>,
      TError,
      { competitionId: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof userJoinsCompetition>>, TError, { competitionId: number }, TContext> => {
  const mutationOptions = getUserJoinsCompetitionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const organizerAddsParticipant = (
  competitionId: number,
  addParticipantCommand: AddParticipantCommand,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<unknown>(
    {
      url: `/api/competitions/${competitionId}/participants`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: addParticipantCommand,
      signal
    },
    options
  );
};

export const getOrganizerAddsParticipantMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizerAddsParticipant>>,
    TError,
    { competitionId: number; data: AddParticipantCommand },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizerAddsParticipant>>,
  TError,
  { competitionId: number; data: AddParticipantCommand },
  TContext
> => {
  const mutationKey = ['organizerAddsParticipant'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizerAddsParticipant>>,
    { competitionId: number; data: AddParticipantCommand }
  > = (props) => {
    const { competitionId, data } = props ?? {};

    return organizerAddsParticipant(competitionId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizerAddsParticipantMutationResult = NonNullable<Awaited<ReturnType<typeof organizerAddsParticipant>>>;
export type OrganizerAddsParticipantMutationBody = AddParticipantCommand;
export type OrganizerAddsParticipantMutationError = ProblemDetails;

export const useOrganizerAddsParticipant = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof organizerAddsParticipant>>,
      TError,
      { competitionId: number; data: AddParticipantCommand },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof organizerAddsParticipant>>,
  TError,
  { competitionId: number; data: AddParticipantCommand },
  TContext
> => {
  const mutationOptions = getOrganizerAddsParticipantMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const organizerRemovesParticipant = (
  competitionId: number,
  participantEntryId: number,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    { url: `/api/competitions/${competitionId}/participants/${participantEntryId}`, method: 'DELETE' },
    options
  );
};

export const getOrganizerRemovesParticipantMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizerRemovesParticipant>>,
    TError,
    { competitionId: number; participantEntryId: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizerRemovesParticipant>>,
  TError,
  { competitionId: number; participantEntryId: number },
  TContext
> => {
  const mutationKey = ['organizerRemovesParticipant'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizerRemovesParticipant>>,
    { competitionId: number; participantEntryId: number }
  > = (props) => {
    const { competitionId, participantEntryId } = props ?? {};

    return organizerRemovesParticipant(competitionId, participantEntryId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizerRemovesParticipantMutationResult = NonNullable<
  Awaited<ReturnType<typeof organizerRemovesParticipant>>
>;

export type OrganizerRemovesParticipantMutationError = ProblemDetails;

export const useOrganizerRemovesParticipant = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof organizerRemovesParticipant>>,
      TError,
      { competitionId: number; participantEntryId: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof organizerRemovesParticipant>>,
  TError,
  { competitionId: number; participantEntryId: number },
  TContext
> => {
  const mutationOptions = getOrganizerRemovesParticipantMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const organizerApprovesParticipant = (
  competitionId: number,
  participantId: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    { url: `/api/competitions/${competitionId}/participants/${participantId}/approve`, method: 'POST', signal },
    options
  );
};

export const getOrganizerApprovesParticipantMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizerApprovesParticipant>>,
    TError,
    { competitionId: number; participantId: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizerApprovesParticipant>>,
  TError,
  { competitionId: number; participantId: number },
  TContext
> => {
  const mutationKey = ['organizerApprovesParticipant'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizerApprovesParticipant>>,
    { competitionId: number; participantId: number }
  > = (props) => {
    const { competitionId, participantId } = props ?? {};

    return organizerApprovesParticipant(competitionId, participantId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizerApprovesParticipantMutationResult = NonNullable<
  Awaited<ReturnType<typeof organizerApprovesParticipant>>
>;

export type OrganizerApprovesParticipantMutationError = ProblemDetails;

export const useOrganizerApprovesParticipant = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof organizerApprovesParticipant>>,
      TError,
      { competitionId: number; participantId: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof organizerApprovesParticipant>>,
  TError,
  { competitionId: number; participantId: number },
  TContext
> => {
  const mutationOptions = getOrganizerApprovesParticipantMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const organizerRejectsParticipant = (
  competitionId: number,
  participantId: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    { url: `/api/competitions/${competitionId}/participants/${participantId}/reject`, method: 'POST', signal },
    options
  );
};

export const getOrganizerRejectsParticipantMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizerRejectsParticipant>>,
    TError,
    { competitionId: number; participantId: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizerRejectsParticipant>>,
  TError,
  { competitionId: number; participantId: number },
  TContext
> => {
  const mutationKey = ['organizerRejectsParticipant'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizerRejectsParticipant>>,
    { competitionId: number; participantId: number }
  > = (props) => {
    const { competitionId, participantId } = props ?? {};

    return organizerRejectsParticipant(competitionId, participantId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizerRejectsParticipantMutationResult = NonNullable<
  Awaited<ReturnType<typeof organizerRejectsParticipant>>
>;

export type OrganizerRejectsParticipantMutationError = ProblemDetails;

export const useOrganizerRejectsParticipant = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof organizerRejectsParticipant>>,
      TError,
      { competitionId: number; participantId: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof organizerRejectsParticipant>>,
  TError,
  { competitionId: number; participantId: number },
  TContext
> => {
  const mutationOptions = getOrganizerRejectsParticipantMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const organizerAssignsJudge = (
  competitionId: number,
  assignJudgeCommand: AssignJudgeCommand,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<unknown>(
    {
      url: `/api/competitions/${competitionId}/judges`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: assignJudgeCommand,
      signal
    },
    options
  );
};

export const getOrganizerAssignsJudgeMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizerAssignsJudge>>,
    TError,
    { competitionId: number; data: AssignJudgeCommand },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizerAssignsJudge>>,
  TError,
  { competitionId: number; data: AssignJudgeCommand },
  TContext
> => {
  const mutationKey = ['organizerAssignsJudge'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizerAssignsJudge>>,
    { competitionId: number; data: AssignJudgeCommand }
  > = (props) => {
    const { competitionId, data } = props ?? {};

    return organizerAssignsJudge(competitionId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizerAssignsJudgeMutationResult = NonNullable<Awaited<ReturnType<typeof organizerAssignsJudge>>>;
export type OrganizerAssignsJudgeMutationBody = AssignJudgeCommand;
export type OrganizerAssignsJudgeMutationError = ProblemDetails;

export const useOrganizerAssignsJudge = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof organizerAssignsJudge>>,
      TError,
      { competitionId: number; data: AssignJudgeCommand },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof organizerAssignsJudge>>,
  TError,
  { competitionId: number; data: AssignJudgeCommand },
  TContext
> => {
  const mutationOptions = getOrganizerAssignsJudgeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const organizerRemovesJudge = (
  competitionId: number,
  judgeParticipantEntryId: number,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    { url: `/api/competitions/${competitionId}/judges/${judgeParticipantEntryId}`, method: 'DELETE' },
    options
  );
};

export const getOrganizerRemovesJudgeMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizerRemovesJudge>>,
    TError,
    { competitionId: number; judgeParticipantEntryId: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizerRemovesJudge>>,
  TError,
  { competitionId: number; judgeParticipantEntryId: number },
  TContext
> => {
  const mutationKey = ['organizerRemovesJudge'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizerRemovesJudge>>,
    { competitionId: number; judgeParticipantEntryId: number }
  > = (props) => {
    const { competitionId, judgeParticipantEntryId } = props ?? {};

    return organizerRemovesJudge(competitionId, judgeParticipantEntryId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizerRemovesJudgeMutationResult = NonNullable<Awaited<ReturnType<typeof organizerRemovesJudge>>>;

export type OrganizerRemovesJudgeMutationError = ProblemDetails;

export const useOrganizerRemovesJudge = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof organizerRemovesJudge>>,
      TError,
      { competitionId: number; judgeParticipantEntryId: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof organizerRemovesJudge>>,
  TError,
  { competitionId: number; judgeParticipantEntryId: number },
  TContext
> => {
  const mutationOptions = getOrganizerRemovesJudgeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getCompetitionCatches = (
  competitionId: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<CompetitionFishCatchDto[]>(
    { url: `/api/competitions/${competitionId}/catches`, method: 'GET', signal },
    options
  );
};

export const getGetCompetitionCatchesQueryKey = (competitionId: number) => {
  return [`/api/competitions/${competitionId}/catches`] as const;
};

export const getGetCompetitionCatchesQueryOptions = <
  TData = Awaited<ReturnType<typeof getCompetitionCatches>>,
  TError = ProblemDetails
>(
  competitionId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompetitionCatches>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCompetitionCatchesQueryKey(competitionId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCompetitionCatches>>> = ({ signal }) =>
    getCompetitionCatches(competitionId, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!competitionId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCompetitionCatches>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCompetitionCatchesQueryResult = NonNullable<Awaited<ReturnType<typeof getCompetitionCatches>>>;
export type GetCompetitionCatchesQueryError = ProblemDetails;

export function useGetCompetitionCatches<
  TData = Awaited<ReturnType<typeof getCompetitionCatches>>,
  TError = ProblemDetails
>(
  competitionId: number,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompetitionCatches>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompetitionCatches>>,
          TError,
          Awaited<ReturnType<typeof getCompetitionCatches>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCompetitionCatches<
  TData = Awaited<ReturnType<typeof getCompetitionCatches>>,
  TError = ProblemDetails
>(
  competitionId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompetitionCatches>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompetitionCatches>>,
          TError,
          Awaited<ReturnType<typeof getCompetitionCatches>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCompetitionCatches<
  TData = Awaited<ReturnType<typeof getCompetitionCatches>>,
  TError = ProblemDetails
>(
  competitionId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompetitionCatches>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetCompetitionCatches<
  TData = Awaited<ReturnType<typeof getCompetitionCatches>>,
  TError = ProblemDetails
>(
  competitionId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompetitionCatches>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCompetitionCatchesQueryOptions(competitionId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const judgeRecordsFishCatch = (
  competitionId: number,
  recordCompetitionFishCatchCommand: RecordCompetitionFishCatchCommand,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<unknown>(
    {
      url: `/api/competitions/${competitionId}/catches`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: recordCompetitionFishCatchCommand,
      signal
    },
    options
  );
};

export const getJudgeRecordsFishCatchMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof judgeRecordsFishCatch>>,
    TError,
    { competitionId: number; data: RecordCompetitionFishCatchCommand },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof judgeRecordsFishCatch>>,
  TError,
  { competitionId: number; data: RecordCompetitionFishCatchCommand },
  TContext
> => {
  const mutationKey = ['judgeRecordsFishCatch'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof judgeRecordsFishCatch>>,
    { competitionId: number; data: RecordCompetitionFishCatchCommand }
  > = (props) => {
    const { competitionId, data } = props ?? {};

    return judgeRecordsFishCatch(competitionId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type JudgeRecordsFishCatchMutationResult = NonNullable<Awaited<ReturnType<typeof judgeRecordsFishCatch>>>;
export type JudgeRecordsFishCatchMutationBody = RecordCompetitionFishCatchCommand;
export type JudgeRecordsFishCatchMutationError = ProblemDetails;

export const useJudgeRecordsFishCatch = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof judgeRecordsFishCatch>>,
      TError,
      { competitionId: number; data: RecordCompetitionFishCatchCommand },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof judgeRecordsFishCatch>>,
  TError,
  { competitionId: number; data: RecordCompetitionFishCatchCommand },
  TContext
> => {
  const mutationOptions = getJudgeRecordsFishCatchMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const judgeDeletesFishCatch = (
  competitionId: number,
  fishCatchId: number,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    { url: `/api/competitions/${competitionId}/catches/${fishCatchId}`, method: 'DELETE' },
    options
  );
};

export const getJudgeDeletesFishCatchMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof judgeDeletesFishCatch>>,
    TError,
    { competitionId: number; fishCatchId: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof judgeDeletesFishCatch>>,
  TError,
  { competitionId: number; fishCatchId: number },
  TContext
> => {
  const mutationKey = ['judgeDeletesFishCatch'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof judgeDeletesFishCatch>>,
    { competitionId: number; fishCatchId: number }
  > = (props) => {
    const { competitionId, fishCatchId } = props ?? {};

    return judgeDeletesFishCatch(competitionId, fishCatchId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type JudgeDeletesFishCatchMutationResult = NonNullable<Awaited<ReturnType<typeof judgeDeletesFishCatch>>>;

export type JudgeDeletesFishCatchMutationError = ProblemDetails;

export const useJudgeDeletesFishCatch = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof judgeDeletesFishCatch>>,
      TError,
      { competitionId: number; fishCatchId: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof judgeDeletesFishCatch>>,
  TError,
  { competitionId: number; fishCatchId: number },
  TContext
> => {
  const mutationOptions = getJudgeDeletesFishCatchMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const organizerUpdatesCompetitionCategory = (
  competitionId: number,
  competitionCategoryId: number,
  updateCompetitionCategoryCommand: UpdateCompetitionCategoryCommand,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    {
      url: `/api/competitions/${competitionId}/categories/${competitionCategoryId}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateCompetitionCategoryCommand
    },
    options
  );
};

export const getOrganizerUpdatesCompetitionCategoryMutationOptions = <
  TError = ProblemDetails,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof organizerUpdatesCompetitionCategory>>,
    TError,
    { competitionId: number; competitionCategoryId: number; data: UpdateCompetitionCategoryCommand },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof organizerUpdatesCompetitionCategory>>,
  TError,
  { competitionId: number; competitionCategoryId: number; data: UpdateCompetitionCategoryCommand },
  TContext
> => {
  const mutationKey = ['organizerUpdatesCompetitionCategory'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof organizerUpdatesCompetitionCategory>>,
    { competitionId: number; competitionCategoryId: number; data: UpdateCompetitionCategoryCommand }
  > = (props) => {
    const { competitionId, competitionCategoryId, data } = props ?? {};

    return organizerUpdatesCompetitionCategory(competitionId, competitionCategoryId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrganizerUpdatesCompetitionCategoryMutationResult = NonNullable<
  Awaited<ReturnType<typeof organizerUpdatesCompetitionCategory>>
>;
export type OrganizerUpdatesCompetitionCategoryMutationBody = UpdateCompetitionCategoryCommand;
export type OrganizerUpdatesCompetitionCategoryMutationError = ProblemDetails;

export const useOrganizerUpdatesCompetitionCategory = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof organizerUpdatesCompetitionCategory>>,
      TError,
      { competitionId: number; competitionCategoryId: number; data: UpdateCompetitionCategoryCommand },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof organizerUpdatesCompetitionCategory>>,
  TError,
  { competitionId: number; competitionCategoryId: number; data: UpdateCompetitionCategoryCommand },
  TContext
> => {
  const mutationOptions = getOrganizerUpdatesCompetitionCategoryMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
