/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export interface CatchSummaryDto {
  catchId?: number;
  /** @nullable */
  fishSpeciesName?: string | null;
  /** @nullable */
  lengthInCm?: number | null;
  /** @nullable */
  weightInKg?: number | null;
  catchTime?: string;
}
