/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */
import type { CategoryCalculationLogic } from './categoryCalculationLogic';
import type { CategoryEntityType } from './categoryEntityType';
import type { CategoryMetric } from './categoryMetric';
import type { CategoryType } from './categoryType';
import type { ParticipantResultDto } from './participantResultDto';

export interface CategoryResultDto {
  categoryId?: number;
  /** @nullable */
  categoryName?: string | null;
  /** @nullable */
  categoryDescription?: string | null;
  isPrimaryScoring?: boolean;
  categoryType?: CategoryType;
  metric?: CategoryMetric;
  calculationLogic?: CategoryCalculationLogic;
  entityType?: CategoryEntityType;
  /** @nullable */
  fishSpeciesName?: string | null;
  maxWinnersToDisplay?: number;
  /** @nullable */
  metricUnit?: string | null;
  /** @nullable */
  rankings?: ParticipantResultDto[] | null;
}
