/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export interface CompetitionFishCatchDto {
  id?: number;
  competitionId?: number;
  participantId?: number;
  /** @nullable */
  participantName?: string | null;
  judgeId?: number;
  /** @nullable */
  judgeName?: string | null;
  /** @nullable */
  fishSpeciesId?: number | null;
  /** @nullable */
  fishSpeciesName?: string | null;
  /** @nullable */
  fishSpeciesImageUrl?: string | null;
  /** @nullable */
  lengthInCm?: number | null;
  /** @nullable */
  weightInKg?: number | null;
  catchTime?: string;
  createdAt?: string;
  lastModifiedAt?: string;
}
