/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */
import type { ParticipantWithAssignmentDto } from './participantWithAssignmentDto';

export interface CompetitionParticipantsWithAssignmentsDto {
  competitionId?: number;
  /** @nullable */
  competitionName?: string | null;
  canManageAssignments?: boolean;
  /** @nullable */
  participants?: ParticipantWithAssignmentDto[] | null;
  /** @nullable */
  usedSectors?: string[] | null;
  /** @nullable */
  usedStands?: string[] | null;
}
