/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */
import type { CompetitionType } from './competitionType';
import type { SpecialCategoryDefinitionCommandDto } from './specialCategoryDefinitionCommandDto';

export interface CreateCompetitionCommand {
  /** @nullable */
  name?: string | null;
  startTime?: string;
  endTime?: string;
  fisheryId?: number;
  /** @nullable */
  rules?: string | null;
  type?: CompetitionType;
  /** @nullable */
  imageUrl?: string | null;
  /** @nullable */
  imagePublicId?: string | null;
  primaryScoringCategoryDefinitionId?: number;
  /** @nullable */
  primaryScoringFishSpeciesId?: number | null;
  /** @nullable */
  specialCategories?: SpecialCategoryDefinitionCommandDto[] | null;
}
