/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export interface CreateFisheryCommand {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  location?: string | null;
  /** @nullable */
  imageUrl?: string | null;
  /** @nullable */
  imagePublicId?: string | null;
  /** @nullable */
  fishSpeciesIds?: number[] | null;
}
