/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export interface CurrentUserDto {
  id?: number;
  /** @nullable */
  clerkUserId?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  imageUrl?: string | null;
}
