/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export interface FisheryFishSpeciesDto {
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  imageUrl?: string | null;
  catchesCount?: number;
  /** @nullable */
  averageLength?: number | null;
  /** @nullable */
  averageWeight?: number | null;
}
