/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */
import type { FisheryFishSpeciesDto } from './fisheryFishSpeciesDto';
import type { FisheryStatisticsDto } from './fisheryStatisticsDto';

export interface FisheryDetailsDto {
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  location?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  ownerName?: string | null;
  /** @nullable */
  ownerId?: number | null;
  /** @nullable */
  imageUrl?: string | null;
  createdAt?: string;
  /** @nullable */
  lastModifiedAt?: string | null;
  statistics?: FisheryStatisticsDto;
  /** @nullable */
  fishSpecies?: FisheryFishSpeciesDto[] | null;
}
