/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export interface LogbookSizeRangeStatisticsDto {
  /** @nullable */
  rangeName?: string | null;
  minLengthCm?: number;
  maxLengthCm?: number;
  catchCount?: number;
  percentage?: number;
}
