/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export interface LogbookFisheryStatisticsDto {
  fisheryId?: number;
  /** @nullable */
  fisheryName?: string | null;
  catchCount?: number;
  uniqueSpecies?: number;
  /** @nullable */
  totalWeightKg?: number | null;
}
