/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export interface LogbookMonthlyStatisticsDto {
  year?: number;
  month?: number;
  /** @nullable */
  monthName?: string | null;
  catchCount?: number;
  /** @nullable */
  totalWeightKg?: number | null;
  uniqueSpecies?: number;
}
