/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */
import type { LogbookFisheryStatisticsDto } from './logbookFisheryStatisticsDto';
import type { LogbookMonthlyStatisticsDto } from './logbookMonthlyStatisticsDto';
import type { LogbookSizeRangeStatisticsDto } from './logbookSizeRangeStatisticsDto';
import type { LogbookSpeciesStatisticsDto } from './logbookSpeciesStatisticsDto';

export interface LogbookStatisticsDto {
  totalCatches?: number;
  uniqueSpecies?: number;
  uniqueFisheries?: number;
  /** @nullable */
  totalWeightKg?: number | null;
  /** @nullable */
  averageWeightKg?: number | null;
  /** @nullable */
  largestFishWeightKg?: number | null;
  /** @nullable */
  averageLengthCm?: number | null;
  /** @nullable */
  largestFishLengthCm?: number | null;
  /** @nullable */
  firstCatchDate?: string | null;
  /** @nullable */
  lastCatchDate?: string | null;
  /** @nullable */
  topSpecies?: LogbookSpeciesStatisticsDto[] | null;
  /** @nullable */
  topFisheries?: LogbookFisheryStatisticsDto[] | null;
  /** @nullable */
  monthlyBreakdown?: LogbookMonthlyStatisticsDto[] | null;
  /** @nullable */
  sizeRanges?: LogbookSizeRangeStatisticsDto[] | null;
}
