/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export interface LogbookSpeciesStatisticsDto {
  fishSpeciesId?: number;
  /** @nullable */
  speciesName?: string | null;
  catchCount?: number;
  /** @nullable */
  totalWeightKg?: number | null;
  /** @nullable */
  averageWeightKg?: number | null;
  /** @nullable */
  largestWeightKg?: number | null;
  /** @nullable */
  averageLengthCm?: number | null;
  /** @nullable */
  largestLengthCm?: number | null;
}
