/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export type MyCompetitionFilter = (typeof MyCompetitionFilter)[keyof typeof MyCompetitionFilter];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MyCompetitionFilter = {
  All: 'All',
  Active: 'Active',
  Finished: 'Finished',
  Organized: 'Organized',
  Judged: 'Judged'
} as const;
