/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */
import type { MyCompetitionSummaryDto } from './myCompetitionSummaryDto';

export interface MyCompetitionSummaryDtoPaginatedList {
  /** @nullable */
  items?: MyCompetitionSummaryDto[] | null;
  pageNumber?: number;
  readonly totalPages?: number;
  readonly totalCount?: number;
  readonly hasPreviousPage?: boolean;
  readonly hasNextPage?: boolean;
}
