/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export type ParticipantStatus = (typeof ParticipantStatus)[keyof typeof ParticipantStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ParticipantStatus = {
  Waiting: 'Waiting',
  Approved: 'Approved',
  Rejected: 'Rejected'
} as const;
