/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export interface ParticipantWithAssignmentDto {
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  sector?: string | null;
  /** @nullable */
  stand?: string | null;
  isGuest?: boolean;
}
