/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */
import type { BestCatchDetailsDto } from './bestCatchDetailsDto';
import type { CatchSummaryDto } from './catchSummaryDto';

export interface ParticipantResultDto {
  participantId?: number;
  /** @nullable */
  participantName?: string | null;
  position?: number;
  /** @nullable */
  value?: number | null;
  /** @nullable */
  valueDisplay?: string | null;
  catchesCount?: number;
  bestCatch?: BestCatchDetailsDto;
  /** @nullable */
  allCatches?: CatchSummaryDto[] | null;
}
