/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */
import type { PublicResultCategoryWinnerDto } from './publicResultCategoryWinnerDto';

export interface PublicResultSpecialCategoryDto {
  /** @nullable */
  categoryName?: string | null;
  /** @nullable */
  categoryDescription?: string | null;
  /** @nullable */
  winners?: PublicResultCategoryWinnerDto[] | null;
}
