/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export interface PublicResultCategoryWinnerDto {
  participantId?: number;
  /** @nullable */
  participantName?: string | null;
  /** @nullable */
  fishSpeciesName?: string | null;
  /** @nullable */
  value?: number | null;
  /** @nullable */
  unit?: string | null;
}
