/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */
import type { CategoryMetric } from './categoryMetric';
import type { CompetitionStatus } from './competitionStatus';
import type { PublicResultParticipantDto } from './publicResultParticipantDto';
import type { PublicResultSpecialCategoryDto } from './publicResultSpecialCategoryDto';

export interface PublicCompetitionResultsDto {
  competitionId?: number;
  /** @nullable */
  competitionName?: string | null;
  startTime?: string;
  endTime?: string;
  /** @nullable */
  fisheryName?: string | null;
  /** @nullable */
  competitionImageUrl?: string | null;
  status?: CompetitionStatus;
  /** @nullable */
  rules?: string | null;
  /** @nullable */
  primaryScoringCategoryName?: string | null;
  primaryScoringMetric?: CategoryMetric;
  /** @nullable */
  upcomingMessage?: string | null;
  /** @nullable */
  mainRanking?: PublicResultParticipantDto[] | null;
  /** @nullable */
  liveRankingPlaceholderMessage?: string | null;
  /** @nullable */
  specialCategoriesResults?: PublicResultSpecialCategoryDto[] | null;
  /** @nullable */
  finishedChartsPlaceholderMessage?: string | null;
}
