/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */
import type { CategoryResultDto } from './categoryResultDto';
import type { CompetitionStatus } from './competitionStatus';
import type { SectorResultDto } from './sectorResultDto';

export interface PublicCompetitionResultsDto {
  competitionId?: number;
  /** @nullable */
  competitionName?: string | null;
  startTime?: string;
  endTime?: string;
  status?: CompetitionStatus;
  /** @nullable */
  fisheryName?: string | null;
  /** @nullable */
  fisheryLocation?: string | null;
  /** @nullable */
  competitionImageUrl?: string | null;
  totalParticipants?: number;
  totalCatches?: number;
  lastUpdated?: string;
  usesSectors?: boolean;
  /** @nullable */
  categoryResults?: CategoryResultDto[] | null;
  /** @nullable */
  sectorResults?: SectorResultDto[] | null;
}
