/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export interface PublicResultParticipantDto {
  participantId?: number;
  /** @nullable */
  name?: string | null;
  totalScore?: number;
  fishCount?: number;
}
