/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export interface SetToDraftCommand {
  competitionId?: number;
  /** @nullable */
  reason?: string | null;
}
