/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export interface UpdateParticipantAssignmentRequest {
  /** @nullable */
  sector?: string | null;
  /** @nullable */
  stand?: string | null;
}
