/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export interface UpdateLogbookEntryCommand {
  id?: number;
  /** @nullable */
  imageUrl?: string | null;
  /** @nullable */
  imagePublicId?: string | null;
  removeCurrentImage?: boolean;
  /** @nullable */
  catchTime?: string | null;
  /** @nullable */
  lengthInCm?: number | null;
  /** @nullable */
  weightInKg?: number | null;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  fishSpeciesId?: number | null;
  /** @nullable */
  fisheryId?: number | null;
}
