/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export interface UpdateFisheryCommand {
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  location?: string | null;
  /** @nullable */
  imageUrl?: string | null;
  /** @nullable */
  imagePublicId?: string | null;
  removeCurrentImage?: boolean;
  /** @nullable */
  fishSpeciesIds?: number[] | null;
}
