/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export interface UploadSignatureResult {
  /** @nullable */
  signature?: string | null;
  /** @nullable */
  apiKey?: string | null;
  /** @nullable */
  cloudName?: string | null;
  timestamp?: number;
  /** @nullable */
  folderName?: string | null;
  /** @nullable */
  publicId?: string | null;
  /** @nullable */
  uploadUrl?: string | null;
}
